# Generated by Django 4.2.1 on 2023-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created_str',
            field=models.CharField(default='default', max_length=20, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
