# Generated by Django 4.2.1 on 2023-05-12 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_created_at_user_created_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_str',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
